### ISSUE TITLE
JSON Error while doing now

### ISSUE THREAD

**Issue by tammer123** [tonytamps/wow-discord-bot#1]
Could you tell me what's wrong : 
JSONError: Unexpected token '.' at 8:110 in package.json
 && now --public && now scale (now ls | grep -io 'wow-discord-bot-.*\.now\.sh'

**Comment by tonytamps** [comment]
It looks like you've changed the package.json and removed the `\` that was escaping the `\.now\.sh`
take a look at the package.json in the repo.

**Comment by tammer123** [comment]
Those are there, but GitHub didn't show them.
There : with spaces .* \ .now \ .sh'

**Comment by tonytamps** [comment]
You should use backticks when displaying code like that. Check the markdown syntax for code snippet and code blocks.

could you give me more info @tammer123 ?

Windows, Linux or OSX? What command are you actually typing into the terminal?
Can you run the steps in that command individually?

Just give me as much info as possible.

**Comment by tammer123** [comment]
Linux. After i write in 'now' into the terminal.
![jsonerror](https://user-images.githubusercontent.com/12547142/33706854-18ff783a-db3e-11e7-996a-441a6b6b157b.PNG)
Only thing I have changed was in client.js where I changed the default server and region.

**Comment by tonytamps** [comment]
it might be the single quotes on linux or the `grep -io` (grep doesnt have the same flags on every platform)

Easy solution would be to run the steps individually and copy the deployment url:
```javascript
now rm wow-discord-bot -y 
now --public
now ls #copy the url from the deployment here or from the previous command
now scale <url_from_last_step> 1
```

**Comment by tammer123** [comment]
Fixed by removing `\` .

**Comment by tonytamps** [comment]
Nice work @tammer123 - best of luck.
